-- Seed data for sources table
-- Expanded catalog with strong focus on ENGLISH, GERMAN, and FRENCH.
-- Keeps useful SPANISH and PORTUGUESE sources.
-- No Duolingo entries.

INSERT INTO sources (id, name, url, description, category, language)
VALUES
  -- ENGLISH: Core platforms
  (gen_random_uuid(), 'BBC Learning English', 'https://www.bbc.co.uk/learningenglish', 'Structured lessons for grammar, listening, pronunciation, and vocabulary.', 'COMPREHENSION', 'ENGLISH'),
  (gen_random_uuid(), 'VOA Learning English', 'https://learningenglish.voanews.com/', 'News and lessons in learner-friendly English.', 'LISTENING', 'ENGLISH'),
  (gen_random_uuid(), 'British Council LearnEnglish', 'https://learnenglish.britishcouncil.org/', 'Official materials with levels, grammar, and skills practice.', 'COMPREHENSION', 'ENGLISH'),
  (gen_random_uuid(), 'Breaking News English', 'https://breakingnewsenglish.com/', 'News-based reading and listening activities by level.', 'READING', 'ENGLISH'),
  (gen_random_uuid(), 'ELLLO', 'https://elllo.org/', 'Listening library with transcripts and quizzes.', 'LISTENING', 'ENGLISH'),
  (gen_random_uuid(), 'ESL Lab', 'https://www.esl-lab.com/', 'Listening comprehension by difficulty.', 'LISTENING', 'ENGLISH'),
  (gen_random_uuid(), 'TED Talks', 'https://www.ted.com/talks', 'Talks with subtitles/transcripts for advanced comprehension.', 'COMPREHENSION', 'ENGLISH'),
  (gen_random_uuid(), 'NPR Podcasts', 'https://www.npr.org/podcasts-and-shows', 'Authentic podcasts for native-speed listening.', 'LISTENING', 'ENGLISH'),
  (gen_random_uuid(), 'BBC News', 'https://www.bbc.com/news', 'Daily journalism for reading immersion.', 'READING', 'ENGLISH'),
  (gen_random_uuid(), 'The Guardian International', 'https://www.theguardian.com/international', 'Long-form and daily news in English.', 'READING', 'ENGLISH'),
  (gen_random_uuid(), 'Reuters World News', 'https://www.reuters.com/world/', 'Objective news coverage for vocabulary expansion.', 'READING', 'ENGLISH'),
  (gen_random_uuid(), 'Project Gutenberg', 'https://www.gutenberg.org/', 'Free classics for extensive reading.', 'READING', 'ENGLISH'),
  (gen_random_uuid(), 'LibriVox', 'https://librivox.org/', 'Free audiobooks to train sustained listening.', 'LISTENING', 'ENGLISH'),
  (gen_random_uuid(), 'Internet Archive Audio', 'https://archive.org/details/audio', 'Public audio archives and spoken content.', 'LISTENING', 'ENGLISH'),

  -- ENGLISH: Tools and references
  (gen_random_uuid(), 'Cambridge Dictionary', 'https://dictionary.cambridge.org/', 'Definitions, examples, and pronunciation.', 'EXTENSIONS', 'ENGLISH'),
  (gen_random_uuid(), 'Merriam-Webster', 'https://www.merriam-webster.com/', 'Dictionary, usage guidance, and quizzes.', 'EXTENSIONS', 'ENGLISH'),
  (gen_random_uuid(), 'Collins Dictionary', 'https://www.collinsdictionary.com/', 'Dictionary and usage examples.', 'EXTENSIONS', 'ENGLISH'),
  (gen_random_uuid(), 'Oxford Learner''s Dictionaries', 'https://www.oxfordlearnersdictionaries.com/', 'Learner-oriented dictionary and examples.', 'EXTENSIONS', 'ENGLISH'),
  (gen_random_uuid(), 'YouGlish English', 'https://youglish.com/english', 'Real pronunciation examples from native videos.', 'EXTENSIONS', 'ENGLISH'),
  (gen_random_uuid(), 'Forvo English', 'https://forvo.com/languages/en/', 'Native pronunciation examples by word.', 'EXTENSIONS', 'ENGLISH'),
  (gen_random_uuid(), 'EnglishClub', 'https://www.englishclub.com/', 'Independent-study resources by skill.', 'EXTENSIONS', 'ENGLISH'),
  (gen_random_uuid(), 'Perfect English Grammar', 'https://www.perfect-english-grammar.com/', 'Grammar explanations and focused exercises.', 'EXTENSIONS', 'ENGLISH'),
  (gen_random_uuid(), 'Grammarly Blog', 'https://www.grammarly.com/blog/', 'Writing and grammar guides.', 'EXTENSIONS', 'ENGLISH'),
  (gen_random_uuid(), 'Purdue OWL', 'https://owl.purdue.edu/', 'Academic writing and citation guides.', 'EXTENSIONS', 'ENGLISH'),
  (gen_random_uuid(), 'Reddit r/EnglishLearning', 'https://www.reddit.com/r/EnglishLearning/', 'Community support and practical language doubts.', 'EXTENSIONS', 'ENGLISH'),

  -- ENGLISH: Native YouTube and media
  (gen_random_uuid(), 'Easy English (YouTube)', 'https://www.youtube.com/@EasyEnglishVideos', 'Street interviews with subtitles and natural speech.', 'LISTENING', 'ENGLISH'),
  (gen_random_uuid(), 'English with Lucy (YouTube)', 'https://www.youtube.com/@EnglishwithLucy', 'Native-speaker lessons and pronunciation tips.', 'COMPREHENSION', 'ENGLISH'),
  (gen_random_uuid(), 'mmmEnglish (YouTube)', 'https://www.youtube.com/@mmmEnglish_Emma', 'Native-led communication-focused lessons.', 'COMPREHENSION', 'ENGLISH'),
  (gen_random_uuid(), 'Rachel''s English (YouTube)', 'https://www.youtube.com/@rachelsenglish', 'American pronunciation and connected speech.', 'LISTENING', 'ENGLISH'),
  (gen_random_uuid(), 'RealLife English (YouTube)', 'https://www.youtube.com/@RealLifeEnglish1', 'Listening and fluency with authentic speech.', 'LISTENING', 'ENGLISH'),
  (gen_random_uuid(), 'BBC Learning English (YouTube)', 'https://www.youtube.com/@bbclearningenglish', 'Official BBC learning videos.', 'COMPREHENSION', 'ENGLISH'),
  (gen_random_uuid(), 'VOA Learning English (YouTube)', 'https://www.youtube.com/@VOALearningEnglish', 'Official VOA learner content.', 'LISTENING', 'ENGLISH'),
  (gen_random_uuid(), 'TED (YouTube)', 'https://www.youtube.com/@TED', 'Native talks and ideas with subtitles.', 'COMPREHENSION', 'ENGLISH'),
  (gen_random_uuid(), 'NPR (YouTube)', 'https://www.youtube.com/@npr', 'Authentic spoken news and interviews.', 'LISTENING', 'ENGLISH'),
  (gen_random_uuid(), 'CrashCourse (YouTube)', 'https://www.youtube.com/@crashcourse', 'Fast native educational videos.', 'COMPREHENSION', 'ENGLISH'),
  (gen_random_uuid(), 'Kurzgesagt (YouTube)', 'https://www.youtube.com/@kurzgesagt', 'High-quality educational videos in English.', 'COMPREHENSION', 'ENGLISH'),
  (gen_random_uuid(), 'LyricsTraining (English)', 'https://lyricstraining.com/en', 'Music-based listening and vocabulary practice.', 'MUSIC', 'ENGLISH'),
  (gen_random_uuid(), 'Genius', 'https://genius.com/', 'Song lyrics and annotation for vocabulary and culture.', 'MUSIC', 'ENGLISH'),
  (gen_random_uuid(), 'Billboard', 'https://www.billboard.com/', 'Music charts and artist-related reading content.', 'MUSIC', 'ENGLISH'),

  -- GERMAN: Core platforms
  (gen_random_uuid(), 'DW Learn German', 'https://learngerman.dw.com/en/learn-german/s-9528', 'Structured courses and multimedia lessons.', 'COMPREHENSION', 'GERMAN'),
  (gen_random_uuid(), 'Goethe-Institut Exercises', 'https://www.goethe.de/de/spr/ueb.html', 'Official German exercises and exam prep.', 'COMPREHENSION', 'GERMAN'),
  (gen_random_uuid(), 'Tagesschau', 'https://www.tagesschau.de/', 'Native German news for daily immersion.', 'READING', 'GERMAN'),
  (gen_random_uuid(), 'Nachrichtenleicht', 'https://www.nachrichtenleicht.de/', 'Simplified German news for learners.', 'READING', 'GERMAN'),
  (gen_random_uuid(), 'Der Spiegel', 'https://www.spiegel.de/', 'Native journalism for advanced reading.', 'READING', 'GERMAN'),
  (gen_random_uuid(), 'ZEIT Online', 'https://www.zeit.de/', 'Opinion and long-form native articles.', 'READING', 'GERMAN'),
  (gen_random_uuid(), 'Deutschlandfunk', 'https://www.deutschlandfunk.de/', 'Native radio and news listening.', 'LISTENING', 'GERMAN'),
  (gen_random_uuid(), 'ARD Mediathek', 'https://www.ardmediathek.de/', 'Native video catalog for immersion.', 'LISTENING', 'GERMAN'),
  (gen_random_uuid(), 'ARD Audiothek', 'https://www.ardsounds.de/', 'Podcasts and radio in German.', 'LISTENING', 'GERMAN'),
  (gen_random_uuid(), 'DeutschAkademie Online Course', 'https://www.deutschakademie.de/online-deutschkurs/', 'Free CEFR-aligned grammar and vocabulary exercises.', 'COMPREHENSION', 'GERMAN'),
  (gen_random_uuid(), 'Lingolia Deutsch', 'https://www.lingolia.com/de/', 'Grammar explanations and drills.', 'EXTENSIONS', 'GERMAN'),
  (gen_random_uuid(), 'Duden', 'https://www.duden.de/', 'Reference dictionary and orthography.', 'EXTENSIONS', 'GERMAN'),
  (gen_random_uuid(), 'LEO German-English Dictionary', 'https://dict.leo.org/german-english/', 'Bilingual dictionary with examples and forum context.', 'EXTENSIONS', 'GERMAN'),
  (gen_random_uuid(), 'dict.cc', 'https://www.dict.cc/', 'Large bilingual dictionary for quick lookup.', 'EXTENSIONS', 'GERMAN'),
  (gen_random_uuid(), 'Forvo German', 'https://forvo.com/languages/de/', 'Native pronunciation by word.', 'EXTENSIONS', 'GERMAN'),

  -- GERMAN: Native YouTube and media
  (gen_random_uuid(), 'Easy German', 'https://www.easygerman.org/', 'Street interviews with subtitles and native input.', 'LISTENING', 'GERMAN'),
  (gen_random_uuid(), 'Easy German (YouTube)', 'https://www.youtube.com/@EasyGerman', 'Native German speech in real contexts.', 'LISTENING', 'GERMAN'),
  (gen_random_uuid(), 'Deutsch lernen mit der DW (YouTube)', 'https://www.youtube.com/@dwlearngerman', 'Official DW learner channel.', 'COMPREHENSION', 'GERMAN'),
  (gen_random_uuid(), 'MrWissen2go (YouTube)', 'https://www.youtube.com/@MrWissen2go', 'Native educational content for comprehension.', 'COMPREHENSION', 'GERMAN'),
  (gen_random_uuid(), 'maiLab (YouTube)', 'https://www.youtube.com/@maiLab', 'Native science explanations in German.', 'COMPREHENSION', 'GERMAN'),
  (gen_random_uuid(), 'Terra X (YouTube)', 'https://www.youtube.com/@TerraX', 'Documentary-style native content.', 'COMPREHENSION', 'GERMAN'),
  (gen_random_uuid(), 'Tagesschau (YouTube)', 'https://www.youtube.com/@tagesschau', 'Daily German news videos.', 'LISTENING', 'GERMAN'),
  (gen_random_uuid(), 'Deutschlandfunk (YouTube)', 'https://www.youtube.com/@deutschlandfunk', 'Native radio/news segments in video format.', 'LISTENING', 'GERMAN'),
  (gen_random_uuid(), 'Slow German', 'https://slowgerman.com/', 'Slower podcasts for learner listening.', 'LISTENING', 'GERMAN'),
  (gen_random_uuid(), 'Songtexte', 'https://www.songtexte.com/', 'German and international song lyrics.', 'MUSIC', 'GERMAN'),
  (gen_random_uuid(), 'Deutsch Perfekt', 'https://www.deutsch-perfekt.com/', 'News and articles tailored to German learners.', 'READING', 'GERMAN'),
  (gen_random_uuid(), 'MDR Wissen (YouTube)', 'https://www.youtube.com/@MDRWissen', 'Native educational channel in German.', 'COMPREHENSION', 'GERMAN'),

  -- FRENCH: Core platforms
  (gen_random_uuid(), 'TV5MONDE Apprendre le francais', 'https://apprendre.tv5monde.com/fr', 'Video lessons and exercises for self-study.', 'COMPREHENSION', 'FRENCH'),
  (gen_random_uuid(), 'RFI Francais Facile', 'https://francaisfacile.rfi.fr/fr/', 'French-learning content with news focus.', 'LISTENING', 'FRENCH'),
  (gen_random_uuid(), 'Le Monde', 'https://www.lemonde.fr/', 'Native French journalism for reading immersion.', 'READING', 'FRENCH'),
  (gen_random_uuid(), 'France 24 Francais', 'https://www.france24.com/fr/', 'News videos and native articles in French.', 'READING', 'FRENCH'),
  (gen_random_uuid(), 'Franceinfo', 'https://www.francetvinfo.fr/', 'Native current-affairs reading and listening.', 'READING', 'FRENCH'),
  (gen_random_uuid(), 'Radio France', 'https://www.radiofrance.fr/', 'Podcasts and radio ecosystem in French.', 'LISTENING', 'FRENCH'),
  (gen_random_uuid(), 'France Inter', 'https://www.franceinter.fr/', 'Native radio shows and podcasts.', 'LISTENING', 'FRENCH'),
  (gen_random_uuid(), 'InnerFrench', 'https://innerfrench.com/', 'Comprehensible-input podcast and blog.', 'LISTENING', 'FRENCH'),
  (gen_random_uuid(), 'Francais Authentique', 'https://www.francaisauthentique.com/', 'Immersion-first listening and mindset content.', 'LISTENING', 'FRENCH'),
  (gen_random_uuid(), 'Podcast Francais Facile', 'https://www.podcastfrancaisfacile.com/', 'Listening lessons with support material.', 'LISTENING', 'FRENCH'),
  (gen_random_uuid(), 'Le Point du FLE', 'https://www.lepointdufle.net/', 'Curated exercises and teaching resources.', 'COMPREHENSION', 'FRENCH'),
  (gen_random_uuid(), 'Bonjour de France', 'https://www.bonjourdefrance.com/', 'Grammar and vocabulary exercises.', 'EXTENSIONS', 'FRENCH'),
  (gen_random_uuid(), 'Larousse Dictionnaire', 'https://www.larousse.fr/dictionnaires/francais', 'French dictionary and lexical reference.', 'EXTENSIONS', 'FRENCH'),
  (gen_random_uuid(), 'WordReference French-English', 'https://www.wordreference.com/fren/', 'Dictionary and usage forum for French learners.', 'EXTENSIONS', 'FRENCH'),
  (gen_random_uuid(), 'Forvo French', 'https://forvo.com/languages/fr/', 'Native French pronunciation examples.', 'EXTENSIONS', 'FRENCH'),

  -- FRENCH: Native YouTube and media
  (gen_random_uuid(), 'Easy French (YouTube)', 'https://www.youtube.com/@EasyFrench', 'Street interviews and subtitle-supported native speech.', 'LISTENING', 'FRENCH'),
  (gen_random_uuid(), 'HugoDecrypte (YouTube)', 'https://www.youtube.com/@HugoDecrypte', 'Native current affairs for modern vocabulary.', 'COMPREHENSION', 'FRENCH'),
  (gen_random_uuid(), 'francetv slash (YouTube)', 'https://www.youtube.com/@francetvslash', 'Native youth-oriented documentaries and stories.', 'LISTENING', 'FRENCH'),
  (gen_random_uuid(), 'ARTE Francais', 'https://www.arte.tv/fr/', 'High-quality documentaries and cultural programs.', 'COMPREHENSION', 'FRENCH'),
  (gen_random_uuid(), 'FLE avec Pierre (YouTube)', 'https://www.youtube.com/@FLEavecPierre', 'Learner-focused channel with practical lessons.', 'COMPREHENSION', 'FRENCH'),
  (gen_random_uuid(), 'Learn French with Alexa (YouTube)', 'https://www.youtube.com/@learnfrenchwithalexa', 'French explanations and learner-focused lessons.', 'COMPREHENSION', 'FRENCH'),
  (gen_random_uuid(), 'French Mornings with Elisa (YouTube)', 'https://www.youtube.com/@FrenchmorningswithElisa', 'Comprehensible French content for daily practice.', 'LISTENING', 'FRENCH'),
  (gen_random_uuid(), 'France 24 (YouTube FR)', 'https://www.youtube.com/@FRANCE24', 'Native French news and interviews.', 'LISTENING', 'FRENCH'),
  (gen_random_uuid(), 'RFI (YouTube)', 'https://www.youtube.com/@RFI', 'Native French news clips and reports.', 'LISTENING', 'FRENCH'),
  (gen_random_uuid(), 'LyricsTraining (French)', 'https://lyricstraining.com/fr', 'Music-based French listening practice.', 'MUSIC', 'FRENCH'),

  -- SPANISH: kept and expanded
  (gen_random_uuid(), 'El Pais', 'https://elpais.com/', 'Native Spanish journalism for reading immersion.', 'READING', 'SPANISH'),
  (gen_random_uuid(), 'BBC Mundo', 'https://www.bbc.com/mundo', 'Daily news in Spanish.', 'READING', 'SPANISH'),
  (gen_random_uuid(), 'RTVE Play', 'https://www.rtve.es/play/', 'Spanish TV and radio for immersion.', 'LISTENING', 'SPANISH'),
  (gen_random_uuid(), 'SpanishPod101', 'https://www.spanishpod101.com/', 'Podcast-driven listening practice.', 'LISTENING', 'SPANISH'),
  (gen_random_uuid(), 'StudySpanish', 'https://www.studyspanish.com/', 'Structured grammar lessons and practice.', 'EXTENSIONS', 'SPANISH'),
  (gen_random_uuid(), 'Dreaming Spanish', 'https://www.dreamingspanish.com/', 'Comprehensible-input videos.', 'COMPREHENSION', 'SPANISH'),
  (gen_random_uuid(), 'Easy Spanish (YouTube)', 'https://www.youtube.com/@EasySpanish', 'Native street interviews with subtitles.', 'LISTENING', 'SPANISH'),
  (gen_random_uuid(), 'WordReference Spanish', 'https://www.wordreference.com/es/', 'Dictionary and usage forum.', 'EXTENSIONS', 'SPANISH'),
  (gen_random_uuid(), 'RAE Diccionario', 'https://dle.rae.es/', 'Official Spanish language dictionary.', 'EXTENSIONS', 'SPANISH'),
  (gen_random_uuid(), 'Forvo Spanish', 'https://forvo.com/languages/es/', 'Native pronunciation reference.', 'EXTENSIONS', 'SPANISH'),
  (gen_random_uuid(), 'Easy Spanish Podcast', 'https://www.easyspanish.fm/', 'Podcast for Spanish listening practice.', 'LISTENING', 'SPANISH'),
  (gen_random_uuid(), 'LyricsTraining (Spanish)', 'https://lyricstraining.com/es', 'Music-based Spanish practice.', 'MUSIC', 'SPANISH'),

  -- PORTUGUESE: kept and expanded
  (gen_random_uuid(), 'BBC News Brasil', 'https://www.bbc.com/portuguese', 'Native-level Brazilian Portuguese news.', 'READING', 'PORTUGUESE'),
  (gen_random_uuid(), 'Nexo Jornal', 'https://www.nexojornal.com.br/', 'Long-form journalism in Portuguese.', 'READING', 'PORTUGUESE'),
  (gen_random_uuid(), 'G1', 'https://g1.globo.com/', 'High-volume native daily news content.', 'READING', 'PORTUGUESE'),
  (gen_random_uuid(), 'Radio CBN Podcasts', 'https://cbn.globoradio.globo/podcasts/', 'Native Brazilian podcasts.', 'LISTENING', 'PORTUGUESE'),
  (gen_random_uuid(), 'Conjuguemos Portuguese', 'https://conjuguemos.com/', 'Verb and grammar drills useful for Portuguese learners.', 'EXTENSIONS', 'PORTUGUESE'),
  (gen_random_uuid(), 'LingQ Portuguese', 'https://www.lingq.com/', 'Reading/listening with vocabulary tracking.', 'READING', 'PORTUGUESE'),
  (gen_random_uuid(), 'Easy Portuguese (YouTube)', 'https://www.youtube.com/@EasyPortugueseVideos', 'Native street interviews with subtitles.', 'LISTENING', 'PORTUGUESE'),
  (gen_random_uuid(), 'Forvo Portuguese', 'https://forvo.com/languages/pt/', 'Native pronunciation examples.', 'EXTENSIONS', 'PORTUGUESE'),
  (gen_random_uuid(), 'Pratica Portugues', 'https://praticaportugues.com/', 'Portuguese lessons and listening resources.', 'COMPREHENSION', 'PORTUGUESE'),
  (gen_random_uuid(), 'Portuguese with Leo (YouTube)', 'https://www.youtube.com/@portuguesewithleo', 'European Portuguese listening and speaking content.', 'LISTENING', 'PORTUGUESE'),
  (gen_random_uuid(), 'PortuguesePod101', 'https://www.portuguesepod101.com/', 'Podcast-based Portuguese lessons.', 'LISTENING', 'PORTUGUESE'),
  (gen_random_uuid(), 'LyricsTraining (Portuguese)', 'https://lyricstraining.com/pt', 'Music-based Portuguese listening and vocab.', 'MUSIC', 'PORTUGUESE'),

  -- ENGLISH: additional high-value autodidact resources
  (gen_random_uuid(), 'engVid', 'https://www.engvid.com/', 'Large library of practical video lessons by native teachers.', 'COMPREHENSION', 'ENGLISH'),
  (gen_random_uuid(), 'News in Levels', 'https://www.newsinlevels.com/', 'Daily news rewritten by proficiency level.', 'READING', 'ENGLISH'),
  (gen_random_uuid(), 'Listen A Minute', 'https://listenaminute.com/', 'Short listening tracks with comprehension tasks.', 'LISTENING', 'ENGLISH'),
  (gen_random_uuid(), 'Luke''s English Podcast', 'https://teacherluke.co.uk/', 'Long-form listening content with natural spoken English.', 'LISTENING', 'ENGLISH'),
  (gen_random_uuid(), 'All Ears English', 'https://www.allearsenglish.com/', 'Podcast episodes focused on real communication.', 'LISTENING', 'ENGLISH'),
  (gen_random_uuid(), 'The New York Times', 'https://www.nytimes.com/', 'High-quality native reading material for advanced learners.', 'READING', 'ENGLISH'),
  (gen_random_uuid(), 'MIT OpenCourseWare', 'https://ocw.mit.edu/', 'Academic lectures and materials in authentic English.', 'COMPREHENSION', 'ENGLISH'),
  (gen_random_uuid(), 'Khan Academy', 'https://www.khanacademy.org/', 'Topic-based native English explanations with subtitles.', 'COMPREHENSION', 'ENGLISH'),
  (gen_random_uuid(), 'AnkiWeb', 'https://ankiweb.net/', 'Spaced repetition platform for long-term memory.', 'EXTENSIONS', 'ENGLISH'),
  (gen_random_uuid(), 'Language Reactor', 'https://www.languagereactor.com/', 'Dual subtitles and lookup while watching native videos.', 'EXTENSIONS', 'ENGLISH'),
  (gen_random_uuid(), 'Tatoeba', 'https://tatoeba.org/', 'Sentence database for context-rich examples.', 'EXTENSIONS', 'ENGLISH'),
  (gen_random_uuid(), 'Reverso Context (English)', 'https://context.reverso.net/translation/', 'Contextual bilingual examples from real text.', 'EXTENSIONS', 'ENGLISH'),

  -- GERMAN: additional high-value autodidact resources
  (gen_random_uuid(), 'Nicos Weg', 'https://learngerman.dw.com/de/nicos-weg/c-36519687', 'Story-based German course from A1 to B1.', 'COMPREHENSION', 'GERMAN'),
  (gen_random_uuid(), 'Deutschtrainer (DW)', 'https://learngerman.dw.com/de/deutschtrainer/c-399023', 'Everyday German vocabulary and pronunciation units.', 'COMPREHENSION', 'GERMAN'),
  (gen_random_uuid(), 'Langsam gesprochene Nachrichten', 'https://learngerman.dw.com/de/langsam-gesprochene-nachrichten/s-60040332', 'News read more slowly for listening practice.', 'LISTENING', 'GERMAN'),
  (gen_random_uuid(), 'ZDF Nachrichten', 'https://www.zdf.de/nachrichten', 'Native news videos and articles.', 'READING', 'GERMAN'),
  (gen_random_uuid(), 'BR24', 'https://www.br.de/nachrichten/', 'Regional and national news in German.', 'READING', 'GERMAN'),
  (gen_random_uuid(), 'ARTE Deutsch', 'https://www.arte.tv/de/', 'Native documentaries and cultural content in German.', 'COMPREHENSION', 'GERMAN'),
  (gen_random_uuid(), 'Linguee German-English', 'https://www.linguee.com/german-english', 'Dictionary with contextual bilingual examples.', 'EXTENSIONS', 'GERMAN'),
  (gen_random_uuid(), 'Reverso Context (German)', 'https://context.reverso.net/translation/german-english/', 'Context examples for German usage.', 'EXTENSIONS', 'GERMAN'),
  (gen_random_uuid(), 'Learn German with Anja (YouTube)', 'https://www.youtube.com/@LearnGermanwithAnja', 'Popular learner-focused German channel.', 'COMPREHENSION', 'GERMAN'),
  (gen_random_uuid(), 'Deutsch mit Marija (YouTube)', 'https://www.youtube.com/@DeutschmitMarija', 'Grammar and exam-focused German explanations.', 'COMPREHENSION', 'GERMAN'),
  (gen_random_uuid(), 'YourGermanTeacher (YouTube)', 'https://www.youtube.com/@yourgermanteacher', 'Step-by-step German grammar and usage lessons.', 'COMPREHENSION', 'GERMAN'),
  (gen_random_uuid(), 'EasyDeutsch (YouTube)', 'https://www.youtube.com/@EasyDeutsch', 'Clear grammar lessons and practical German examples.', 'COMPREHENSION', 'GERMAN'),

  -- FRENCH: additional high-value autodidact resources
  (gen_random_uuid(), 'Le Figaro', 'https://www.lefigaro.fr/', 'Native French news and opinion for reading immersion.', 'READING', 'FRENCH'),
  (gen_random_uuid(), 'TV5MONDE Info', 'https://information.tv5monde.com/', 'French-language world news and reports.', 'READING', 'FRENCH'),
  (gen_random_uuid(), 'France Culture', 'https://www.radiofrance.fr/franceculture', 'Native podcasts and long-form cultural audio.', 'LISTENING', 'FRENCH'),
  (gen_random_uuid(), 'Journal en francais facile (RFI)', 'https://francaisfacile.rfi.fr/fr/podcasts/journal-en-francais-facile/', 'Regular learner-oriented French news podcast.', 'LISTENING', 'FRENCH'),
  (gen_random_uuid(), 'Dictionnaire Le Robert', 'https://dictionnaire.lerobert.com/', 'French dictionary and usage references.', 'EXTENSIONS', 'FRENCH'),
  (gen_random_uuid(), 'Linguee French-English', 'https://www.linguee.com/french-english', 'Bilingual dictionary with context examples.', 'EXTENSIONS', 'FRENCH'),
  (gen_random_uuid(), 'Reverso Context (French)', 'https://context.reverso.net/translation/french-english/', 'Contextual examples for French usage.', 'EXTENSIONS', 'FRENCH'),
  (gen_random_uuid(), 'Francais avec Pierre', 'https://www.francaisavecpierre.com/', 'Well-structured lessons for autodidact learners.', 'COMPREHENSION', 'FRENCH'),
  (gen_random_uuid(), 'Francais Facile', 'https://www.francaisfacile.com/', 'Grammar and vocabulary exercises with corrections.', 'EXTENSIONS', 'FRENCH'),
  (gen_random_uuid(), 'Coffee Break French', 'https://coffeebreaklanguages.com/coffeebreakfrench/', 'Progressive podcast for independent French study.', 'LISTENING', 'FRENCH'),
  (gen_random_uuid(), 'Piece of French (YouTube)', 'https://www.youtube.com/@pieceoffrench', 'Native French stories and real-life explanations.', 'LISTENING', 'FRENCH'),
  (gen_random_uuid(), 'French Comprehensible Input (YouTube)', 'https://www.youtube.com/@FrenchComprehensibleInput', 'Input-rich French videos for natural acquisition.', 'LISTENING', 'FRENCH'),

  -- SPANISH: extra keep
  (gen_random_uuid(), 'El Mundo', 'https://www.elmundo.es/', 'Native Spanish journalism for reading practice.', 'READING', 'SPANISH'),
  (gen_random_uuid(), 'Cadena SER Podcasts', 'https://cadenaser.com/podcast/', 'Native Spanish podcasts and radio programs.', 'LISTENING', 'SPANISH'),

  -- PORTUGUESE: extra keep
  (gen_random_uuid(), 'Agencia Brasil', 'https://agenciabrasil.ebc.com.br/', 'Public Brazilian news source in native Portuguese.', 'READING', 'PORTUGUESE'),
  (gen_random_uuid(), 'NerdCast', 'https://jovemnerd.com.br/nerdcast/', 'Popular Brazilian podcast for natural listening input.', 'LISTENING', 'PORTUGUESE'),

  -- ENGLISH: regional/native variety + writing/pronunciation/exercises
  (gen_random_uuid(), 'CBC News', 'https://www.cbc.ca/news', 'Canadian English news for regional vocabulary and style.', 'READING', 'ENGLISH'),
  (gen_random_uuid(), 'ABC News Australia', 'https://www.abc.net.au/news', 'Australian English input from native journalism.', 'READING', 'ENGLISH'),
  (gen_random_uuid(), 'BBC Sounds', 'https://www.bbc.co.uk/sounds', 'Native UK radio and podcasts across many accents.', 'LISTENING', 'ENGLISH'),
  (gen_random_uuid(), 'Poetry Foundation', 'https://www.poetryfoundation.org/', 'Poems and audio readings for literary English immersion.', 'READING', 'ENGLISH'),
  (gen_random_uuid(), 'Poets.org', 'https://poets.org/', 'Poetry archive and readings for advanced vocabulary.', 'READING', 'ENGLISH'),
  (gen_random_uuid(), 'LangCorrect', 'https://langcorrect.com/', 'Writing journal with corrections from native speakers.', 'EXTENSIONS', 'ENGLISH'),
  (gen_random_uuid(), 'Journaly', 'https://journaly.com/', 'Write posts and receive corrections from the community.', 'EXTENSIONS', 'ENGLISH'),
  (gen_random_uuid(), 'Test-English', 'https://test-english.com/', 'Grammar, vocabulary, and exam-style exercises.', 'COMPREHENSION', 'ENGLISH'),
  (gen_random_uuid(), 'Exam English', 'https://www.examenglish.com/', 'Practice tests for IELTS, TOEFL, and Cambridge exams.', 'COMPREHENSION', 'ENGLISH'),
  (gen_random_uuid(), 'TalkEnglish', 'https://www.talkenglish.com/', 'Speaking patterns and practical listening drills.', 'LISTENING', 'ENGLISH'),
  (gen_random_uuid(), 'Rachel''s English Sounds', 'https://rachelsenglish.com/sounds/', 'Pronunciation drills for American English sounds.', 'EXTENSIONS', 'ENGLISH'),
  (gen_random_uuid(), 'Reddit r/languagelearning', 'https://www.reddit.com/r/languagelearning/', 'General self-study strategies and resource discussions.', 'EXTENSIONS', 'ENGLISH'),

  -- GERMAN: Germany + Austria + Switzerland + skills
  (gen_random_uuid(), 'ORF', 'https://orf.at/', 'Austrian German news and media for regional exposure.', 'READING', 'GERMAN'),
  (gen_random_uuid(), 'ORF TVthek', 'https://tvthek.orf.at/', 'Austrian TV catalog for listening and comprehension.', 'LISTENING', 'GERMAN'),
  (gen_random_uuid(), 'Der Standard', 'https://www.derstandard.at/', 'Austrian journalism in German.', 'READING', 'GERMAN'),
  (gen_random_uuid(), 'SRF News', 'https://www.srf.ch/news', 'Swiss German-region news portal in Standard German.', 'READING', 'GERMAN'),
  (gen_random_uuid(), 'SRF Audio', 'https://www.srf.ch/audio', 'Swiss audio/radio programs in German.', 'LISTENING', 'GERMAN'),
  (gen_random_uuid(), 'Neue Zurcher Zeitung', 'https://www.nzz.ch/', 'Swiss high-quality newspaper in German.', 'READING', 'GERMAN'),
  (gen_random_uuid(), 'Swissinfo DE', 'https://www.swissinfo.ch/ger', 'Swiss reporting in German with international topics.', 'READING', 'GERMAN'),
  (gen_random_uuid(), 'Projekt Gutenberg-DE', 'https://www.projekt-gutenberg.org/', 'German literary texts for extensive reading.', 'READING', 'GERMAN'),
  (gen_random_uuid(), 'Deutsche Lyrik', 'https://www.deutschelyrik.de/', 'Poetry archive for literary German.', 'READING', 'GERMAN'),
  (gen_random_uuid(), 'Schubert-Verlag Ubungen', 'https://www.schubert-verlag.de/aufgaben/uebungen_a1/a1_uebungen_index.htm', 'Grammar and vocabulary exercises by level.', 'COMPREHENSION', 'GERMAN'),
  (gen_random_uuid(), 'Mein Deutschbuch', 'https://mein-deutschbuch.de/', 'Detailed grammar explanations and exercises.', 'EXTENSIONS', 'GERMAN'),
  (gen_random_uuid(), 'Duden Mentor', 'https://mentor.duden.de/', 'Writing correction assistant for German texts.', 'EXTENSIONS', 'GERMAN'),
  (gen_random_uuid(), 'LanguageTool German', 'https://languagetool.org/de', 'Grammar/style checker to improve writing.', 'EXTENSIONS', 'GERMAN'),
  (gen_random_uuid(), 'Foren Deutsch als Fremdsprache', 'https://www.deutsch-als-fremdsprache.de/', 'Forum and resources for German learners.', 'EXTENSIONS', 'GERMAN'),
  (gen_random_uuid(), 'Reddit r/German', 'https://www.reddit.com/r/German/', 'Community help and resource exchange for German learners.', 'EXTENSIONS', 'GERMAN'),

  -- FRENCH: France + Quebec + Switzerland + skills
  (gen_random_uuid(), 'Radio-Canada Info', 'https://ici.radio-canada.ca/', 'Quebec/Canada French news and media.', 'READING', 'FRENCH'),
  (gen_random_uuid(), 'Radio-Canada OHdio', 'https://ici.radio-canada.ca/ohdio', 'Quebec French radio and podcasts.', 'LISTENING', 'FRENCH'),
  (gen_random_uuid(), 'La Presse', 'https://www.lapresse.ca/', 'Quebec French journalism for reading immersion.', 'READING', 'FRENCH'),
  (gen_random_uuid(), 'Le Devoir', 'https://www.ledevoir.com/', 'Quebec newspaper with high-quality French prose.', 'READING', 'FRENCH'),
  (gen_random_uuid(), 'RTS Info', 'https://www.rts.ch/info/', 'Swiss French news portal.', 'READING', 'FRENCH'),
  (gen_random_uuid(), 'RTS Audio', 'https://www.rts.ch/audio/', 'Swiss French radio and podcast programs.', 'LISTENING', 'FRENCH'),
  (gen_random_uuid(), 'Le Temps', 'https://www.letemps.ch/', 'Swiss French journalism and analysis.', 'READING', 'FRENCH'),
  (gen_random_uuid(), 'Swissinfo FR', 'https://www.swissinfo.ch/fre', 'Swiss reporting in French.', 'READING', 'FRENCH'),
  (gen_random_uuid(), 'Wikisource Francais', 'https://fr.wikisource.org/', 'Public-domain French literature and texts.', 'READING', 'FRENCH'),
  (gen_random_uuid(), 'Poesie Francaise', 'https://www.poesie-francaise.fr/', 'French poetry archive for literary practice.', 'READING', 'FRENCH'),
  (gen_random_uuid(), 'Kwiziq French', 'https://french.kwiziq.com/', 'Adaptive grammar practice for French.', 'COMPREHENSION', 'FRENCH'),
  (gen_random_uuid(), 'TV5MONDE Exercices', 'https://apprendre.tv5monde.com/fr/exercices', 'Interactive grammar/listening exercises by level.', 'COMPREHENSION', 'FRENCH'),
  (gen_random_uuid(), 'LanguageTool French', 'https://languagetool.org/fr', 'Grammar/style checker for French writing.', 'EXTENSIONS', 'FRENCH'),
  (gen_random_uuid(), 'Reddit r/French', 'https://www.reddit.com/r/French/', 'Community corrections and resource exchange for French learners.', 'EXTENSIONS', 'FRENCH'),
  (gen_random_uuid(), 'maprofdefrancais (YouTube)', 'https://www.youtube.com/@maprofdefrancais', 'French teacher channel for grammar and usage.', 'COMPREHENSION', 'FRENCH'),
  (gen_random_uuid(), 'French School TV (YouTube)', 'https://www.youtube.com/@FrenchSchoolTV', 'Pronunciation and lesson videos for learners.', 'COMPREHENSION', 'FRENCH');
